name: Ring-MQTT with Video Streaming
version: 5.0.5
slug: ring_mqtt
description: Integrate Ring Devices into Home Assistant via MQTT and RTSP
startup: application
boot: auto
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
url: 'https://github.com/tsightler/ring-mqtt-ha-addon'
image: 'tsightler/ring-mqtt'
webui: 'http://[HOST]:[PORT:55123]/'
ingress: true
ingress_port: 55123
services:
  - 'mqtt:need'
map:
  - config
  - ssl
watchdog: 'http://[HOST]:[PORT:55123]/'
ports:
  8554/tcp: null
  8555/tcp: 8555
ports_description:
  8554/tcp: 'RTSP Server External Port (IMPORTANT: Configure livestream username/password before enabling!)'
  8555/tcp: 'Go2RTC port for WebRTC (required only if using Home RTSPtoWebRTC Home Assistant integration)'
init: false
hassio_api: true
video: true
options:
  mqtt_url: 'mqtt://auto_username:auto_password@auto_hostname'
  mqtt_options: ''
  livestream_user: ''
  livestream_pass: ''
  disarm_code: ''
  enable_cameras: true
  enable_modes: false
  enable_panic: false
  branch: addon
  debug: ring-*
  location_ids: []
schema:
  mqtt_url: url
  mqtt_options: str
  livestream_user: str
  livestream_pass: password
  disarm_code: password
  enable_cameras: bool
  enable_modes: bool
  enable_panic: bool
  branch: str
  debug: str
  location_ids: 
    - str
